// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: dts/internal/internal_service.proto

// 1. 定义包名

package internal

import (
	service "dts-cli/pkg/proto/service"
	task "dts-cli/pkg/proto/task"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Worker 的唯一 ID，可以是 hostname、pod-name 或 UUID
	WorkerId string `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	// Worker 的 gRPC 监听地址，Scheduler 会用这个地址反向调用它
	Address       string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` // e.g., "10.0.1.5:9091"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_dts_internal_internal_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dts_internal_internal_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_dts_internal_internal_service_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *service.RpcRespHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_dts_internal_internal_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dts_internal_internal_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_dts_internal_internal_service_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetHeader() *service.RpcRespHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type HeartbeatRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	WorkerId string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	// Worker 可以选择性地上报自己的负载情况
	RunningTaskCount int32   `protobuf:"varint,2,opt,name=running_task_count,json=runningTaskCount,proto3" json:"running_task_count,omitempty"` // 当前正在执行的任务数
	CpuUsagePercent  float32 `protobuf:"fixed32,3,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`   // CPU 使用率
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_dts_internal_internal_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dts_internal_internal_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_dts_internal_internal_service_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetRunningTaskCount() int32 {
	if x != nil {
		return x.RunningTaskCount
	}
	return 0
}

func (x *HeartbeatRequest) GetCpuUsagePercent() float32 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

type HeartbeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Scheduler 可以在响应中携带一些指令，
	// e.g., "STOP_ACCEPTING_TASKS" (用于优雅下线)
	Header        *service.RpcRespHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_dts_internal_internal_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dts_internal_internal_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_dts_internal_internal_service_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetHeader() *service.RpcRespHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type UpdateTaskStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 哪个任务完成了
	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// 任务的最终状态
	// 只能是 dts.task.TaskState 中的终态：
	// SUCCESS (2), FAILED (3), TIMEOUT (4)
	FinalState task.TaskState `protobuf:"varint,2,opt,name=final_state,json=finalState,proto3,enum=dts.task.TaskState" json:"final_state,omitempty"`
	// 如果是 FAILED (3)，这里是错误信息
	ErrorMsg string `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	// 如果是 SUCCESS (2)，这里是任务的 JSON 格式的执行结果
	// 对应你数据库中的 task.result (jsonb)
	ResultJson    string `protobuf:"bytes,4,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	JobId         string `protobuf:"bytes,5,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	RetryCount    int32  `protobuf:"varint,6,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskStatusRequest) Reset() {
	*x = UpdateTaskStatusRequest{}
	mi := &file_dts_internal_internal_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskStatusRequest) ProtoMessage() {}

func (x *UpdateTaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dts_internal_internal_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_dts_internal_internal_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateTaskStatusRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *UpdateTaskStatusRequest) GetFinalState() task.TaskState {
	if x != nil {
		return x.FinalState
	}
	return task.TaskState(0)
}

func (x *UpdateTaskStatusRequest) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *UpdateTaskStatusRequest) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *UpdateTaskStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *UpdateTaskStatusRequest) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

type UpdateTaskStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *service.RpcRespHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskStatusResponse) Reset() {
	*x = UpdateTaskStatusResponse{}
	mi := &file_dts_internal_internal_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskStatusResponse) ProtoMessage() {}

func (x *UpdateTaskStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dts_internal_internal_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateTaskStatusResponse) Descriptor() ([]byte, []int) {
	return file_dts_internal_internal_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateTaskStatusResponse) GetHeader() *service.RpcRespHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type RunTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 派发给 Worker 的完整任务信息
	// Worker 需要 task_id, func_name, func_params, timeout_ms 等
	Task          *task.Task `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunTaskRequest) Reset() {
	*x = RunTaskRequest{}
	mi := &file_dts_internal_internal_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunTaskRequest) ProtoMessage() {}

func (x *RunTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dts_internal_internal_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunTaskRequest.ProtoReflect.Descriptor instead.
func (*RunTaskRequest) Descriptor() ([]byte, []int) {
	return file_dts_internal_internal_service_proto_rawDescGZIP(), []int{6}
}

func (x *RunTaskRequest) GetTask() *task.Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type RunTaskResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 只要 Worker 成功接收了任务，就返回成功
	// 真正的执行结果是通过 SchedulerService.UpdateTaskStatus 异步回调的
	Header        *service.RpcRespHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunTaskResponse) Reset() {
	*x = RunTaskResponse{}
	mi := &file_dts_internal_internal_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunTaskResponse) ProtoMessage() {}

func (x *RunTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dts_internal_internal_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunTaskResponse.ProtoReflect.Descriptor instead.
func (*RunTaskResponse) Descriptor() ([]byte, []int) {
	return file_dts_internal_internal_service_proto_rawDescGZIP(), []int{7}
}

func (x *RunTaskResponse) GetHeader() *service.RpcRespHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

var File_dts_internal_internal_service_proto protoreflect.FileDescriptor

const file_dts_internal_internal_service_proto_rawDesc = "" +
	"\n" +
	"#dts/internal/internal_service.proto\x12\fdts.internal\x1a\x13dts/task/task.proto\x1a\x1edts/service/task_service.proto\x1a\x19dts/task/task_state.proto\"H\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"F\n" +
	"\x10RegisterResponse\x122\n" +
	"\x06header\x18\x01 \x01(\v2\x1a.dts.service.RpcRespHeaderR\x06header\"\x89\x01\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12,\n" +
	"\x12running_task_count\x18\x02 \x01(\x05R\x10runningTaskCount\x12*\n" +
	"\x11cpu_usage_percent\x18\x03 \x01(\x02R\x0fcpuUsagePercent\"G\n" +
	"\x11HeartbeatResponse\x122\n" +
	"\x06header\x18\x01 \x01(\v2\x1a.dts.service.RpcRespHeaderR\x06header\"\xde\x01\n" +
	"\x17UpdateTaskStatusRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x124\n" +
	"\vfinal_state\x18\x02 \x01(\x0e2\x13.dts.task.TaskStateR\n" +
	"finalState\x12\x1b\n" +
	"\terror_msg\x18\x03 \x01(\tR\berrorMsg\x12\x1f\n" +
	"\vresult_json\x18\x04 \x01(\tR\n" +
	"resultJson\x12\x15\n" +
	"\x06job_id\x18\x05 \x01(\tR\x05jobId\x12\x1f\n" +
	"\vretry_count\x18\x06 \x01(\x05R\n" +
	"retryCount\"N\n" +
	"\x18UpdateTaskStatusResponse\x122\n" +
	"\x06header\x18\x01 \x01(\v2\x1a.dts.service.RpcRespHeaderR\x06header\"4\n" +
	"\x0eRunTaskRequest\x12\"\n" +
	"\x04task\x18\x01 \x01(\v2\x0e.dts.task.TaskR\x04task\"E\n" +
	"\x0fRunTaskResponse\x122\n" +
	"\x06header\x18\x01 \x01(\v2\x1a.dts.service.RpcRespHeaderR\x06header2\x8e\x02\n" +
	"\x10SchedulerService\x12I\n" +
	"\bRegister\x12\x1d.dts.internal.RegisterRequest\x1a\x1e.dts.internal.RegisterResponse\x12L\n" +
	"\tHeartbeat\x12\x1e.dts.internal.HeartbeatRequest\x1a\x1f.dts.internal.HeartbeatResponse\x12a\n" +
	"\x10UpdateTaskStatus\x12%.dts.internal.UpdateTaskStatusRequest\x1a&.dts.internal.UpdateTaskStatusResponse2W\n" +
	"\rWorkerService\x12F\n" +
	"\aRunTask\x12\x1c.dts.internal.RunTaskRequest\x1a\x1d.dts.internal.RunTaskResponseB\x1cZ\x1adts-cli/pkg/proto/internalb\x06proto3"

var (
	file_dts_internal_internal_service_proto_rawDescOnce sync.Once
	file_dts_internal_internal_service_proto_rawDescData []byte
)

func file_dts_internal_internal_service_proto_rawDescGZIP() []byte {
	file_dts_internal_internal_service_proto_rawDescOnce.Do(func() {
		file_dts_internal_internal_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dts_internal_internal_service_proto_rawDesc), len(file_dts_internal_internal_service_proto_rawDesc)))
	})
	return file_dts_internal_internal_service_proto_rawDescData
}

var file_dts_internal_internal_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_dts_internal_internal_service_proto_goTypes = []any{
	(*RegisterRequest)(nil),          // 0: dts.internal.RegisterRequest
	(*RegisterResponse)(nil),         // 1: dts.internal.RegisterResponse
	(*HeartbeatRequest)(nil),         // 2: dts.internal.HeartbeatRequest
	(*HeartbeatResponse)(nil),        // 3: dts.internal.HeartbeatResponse
	(*UpdateTaskStatusRequest)(nil),  // 4: dts.internal.UpdateTaskStatusRequest
	(*UpdateTaskStatusResponse)(nil), // 5: dts.internal.UpdateTaskStatusResponse
	(*RunTaskRequest)(nil),           // 6: dts.internal.RunTaskRequest
	(*RunTaskResponse)(nil),          // 7: dts.internal.RunTaskResponse
	(*service.RpcRespHeader)(nil),    // 8: dts.service.RpcRespHeader
	(task.TaskState)(0),              // 9: dts.task.TaskState
	(*task.Task)(nil),                // 10: dts.task.Task
}
var file_dts_internal_internal_service_proto_depIdxs = []int32{
	8,  // 0: dts.internal.RegisterResponse.header:type_name -> dts.service.RpcRespHeader
	8,  // 1: dts.internal.HeartbeatResponse.header:type_name -> dts.service.RpcRespHeader
	9,  // 2: dts.internal.UpdateTaskStatusRequest.final_state:type_name -> dts.task.TaskState
	8,  // 3: dts.internal.UpdateTaskStatusResponse.header:type_name -> dts.service.RpcRespHeader
	10, // 4: dts.internal.RunTaskRequest.task:type_name -> dts.task.Task
	8,  // 5: dts.internal.RunTaskResponse.header:type_name -> dts.service.RpcRespHeader
	0,  // 6: dts.internal.SchedulerService.Register:input_type -> dts.internal.RegisterRequest
	2,  // 7: dts.internal.SchedulerService.Heartbeat:input_type -> dts.internal.HeartbeatRequest
	4,  // 8: dts.internal.SchedulerService.UpdateTaskStatus:input_type -> dts.internal.UpdateTaskStatusRequest
	6,  // 9: dts.internal.WorkerService.RunTask:input_type -> dts.internal.RunTaskRequest
	1,  // 10: dts.internal.SchedulerService.Register:output_type -> dts.internal.RegisterResponse
	3,  // 11: dts.internal.SchedulerService.Heartbeat:output_type -> dts.internal.HeartbeatResponse
	5,  // 12: dts.internal.SchedulerService.UpdateTaskStatus:output_type -> dts.internal.UpdateTaskStatusResponse
	7,  // 13: dts.internal.WorkerService.RunTask:output_type -> dts.internal.RunTaskResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_dts_internal_internal_service_proto_init() }
func file_dts_internal_internal_service_proto_init() {
	if File_dts_internal_internal_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dts_internal_internal_service_proto_rawDesc), len(file_dts_internal_internal_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_dts_internal_internal_service_proto_goTypes,
		DependencyIndexes: file_dts_internal_internal_service_proto_depIdxs,
		MessageInfos:      file_dts_internal_internal_service_proto_msgTypes,
	}.Build()
	File_dts_internal_internal_service_proto = out.File
	file_dts_internal_internal_service_proto_goTypes = nil
	file_dts_internal_internal_service_proto_depIdxs = nil
}
