// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: dts/service/task_service.proto

package service

import (
	error1 "dts-cli/pkg/proto/error"
	task "dts-cli/pkg/proto/task"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_dts_service_task_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dts_service_task_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_dts_service_task_service_proto_rawDescGZIP(), []int{0}
}

func (x *CancelTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetJobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	IncludeTasks  bool                   `protobuf:"varint,2,opt,name=include_tasks,json=includeTasks,proto3" json:"include_tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusRequest) Reset() {
	*x = GetJobStatusRequest{}
	mi := &file_dts_service_task_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusRequest) ProtoMessage() {}

func (x *GetJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dts_service_task_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusRequest.ProtoReflect.Descriptor instead.
func (*GetJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_dts_service_task_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetJobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetJobStatusRequest) GetIncludeTasks() bool {
	if x != nil {
		return x.IncludeTasks
	}
	return false
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_dts_service_task_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dts_service_task_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_dts_service_task_service_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type SubmitDagRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Tasks          []*task.Task           `protobuf:"bytes,2,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Edges          []*task.TaskEdge       `protobuf:"bytes,3,rep,name=edges,proto3" json:"edges,omitempty"`
	ClientId       string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubmitDagRequest) Reset() {
	*x = SubmitDagRequest{}
	mi := &file_dts_service_task_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitDagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitDagRequest) ProtoMessage() {}

func (x *SubmitDagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dts_service_task_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitDagRequest.ProtoReflect.Descriptor instead.
func (*SubmitDagRequest) Descriptor() ([]byte, []int) {
	return file_dts_service_task_service_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitDagRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *SubmitDagRequest) GetTasks() []*task.Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *SubmitDagRequest) GetEdges() []*task.TaskEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *SubmitDagRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// *************** 公共应答头 ***************
type RpcRespHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *error1.Error          `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcRespHeader) Reset() {
	*x = RpcRespHeader{}
	mi := &file_dts_service_task_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcRespHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcRespHeader) ProtoMessage() {}

func (x *RpcRespHeader) ProtoReflect() protoreflect.Message {
	mi := &file_dts_service_task_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcRespHeader.ProtoReflect.Descriptor instead.
func (*RpcRespHeader) Descriptor() ([]byte, []int) {
	return file_dts_service_task_service_proto_rawDescGZIP(), []int{4}
}

func (x *RpcRespHeader) GetError() *error1.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *RpcRespHeader) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// *************** 业务响应体 ***************
type SubmitDagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *RpcRespHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitDagResponse) Reset() {
	*x = SubmitDagResponse{}
	mi := &file_dts_service_task_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitDagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitDagResponse) ProtoMessage() {}

func (x *SubmitDagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dts_service_task_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitDagResponse.ProtoReflect.Descriptor instead.
func (*SubmitDagResponse) Descriptor() ([]byte, []int) {
	return file_dts_service_task_service_proto_rawDescGZIP(), []int{5}
}

func (x *SubmitDagResponse) GetHeader() *RpcRespHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *SubmitDagResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type CancelTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *RpcRespHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"` // 业务结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskResponse) Reset() {
	*x = CancelTaskResponse{}
	mi := &file_dts_service_task_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskResponse) ProtoMessage() {}

func (x *CancelTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dts_service_task_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return file_dts_service_task_service_proto_rawDescGZIP(), []int{6}
}

func (x *CancelTaskResponse) GetHeader() *RpcRespHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CancelTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetJobStatusResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Header *RpcRespHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	JobId  string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State  task.JobState          `protobuf:"varint,3,opt,name=state,proto3,enum=dts.task.JobState" json:"state,omitempty"`
	// 进度条相关
	TotalTasks    int32 `protobuf:"varint,4,opt,name=total_tasks,json=totalTasks,proto3" json:"total_tasks,omitempty"`
	FinishedTasks int32 `protobuf:"varint,5,opt,name=finished_tasks,json=finishedTasks,proto3" json:"finished_tasks,omitempty"`
	// 详情列表 (仅当 request.include_tasks = true 时填充)
	TaskDetails []*task.TaskRuntimeDetail `protobuf:"bytes,6,rep,name=task_details,json=taskDetails,proto3" json:"task_details,omitempty"`
	// 整个 Job 的提交时间和结束时间
	SubmitTime    int64 `protobuf:"varint,7,opt,name=submit_time,json=submitTime,proto3" json:"submit_time,omitempty"`
	FinishTime    int64 `protobuf:"varint,8,opt,name=finish_time,json=finishTime,proto3" json:"finish_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusResponse) Reset() {
	*x = GetJobStatusResponse{}
	mi := &file_dts_service_task_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusResponse) ProtoMessage() {}

func (x *GetJobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dts_service_task_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusResponse.ProtoReflect.Descriptor instead.
func (*GetJobStatusResponse) Descriptor() ([]byte, []int) {
	return file_dts_service_task_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetJobStatusResponse) GetHeader() *RpcRespHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetJobStatusResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetJobStatusResponse) GetState() task.JobState {
	if x != nil {
		return x.State
	}
	return task.JobState(0)
}

func (x *GetJobStatusResponse) GetTotalTasks() int32 {
	if x != nil {
		return x.TotalTasks
	}
	return 0
}

func (x *GetJobStatusResponse) GetFinishedTasks() int32 {
	if x != nil {
		return x.FinishedTasks
	}
	return 0
}

func (x *GetJobStatusResponse) GetTaskDetails() []*task.TaskRuntimeDetail {
	if x != nil {
		return x.TaskDetails
	}
	return nil
}

func (x *GetJobStatusResponse) GetSubmitTime() int64 {
	if x != nil {
		return x.SubmitTime
	}
	return 0
}

func (x *GetJobStatusResponse) GetFinishTime() int64 {
	if x != nil {
		return x.FinishTime
	}
	return 0
}

// 流式返回：同样带公共头
type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *RpcRespHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Task          *task.Task             `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_dts_service_task_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_dts_service_task_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_dts_service_task_service_proto_rawDescGZIP(), []int{8}
}

func (x *TaskResult) GetHeader() *RpcRespHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *TaskResult) GetTask() *task.Task {
	if x != nil {
		return x.Task
	}
	return nil
}

var File_dts_service_task_service_proto protoreflect.FileDescriptor

const file_dts_service_task_service_proto_rawDesc = "" +
	"\n" +
	"\x1edts/service/task_service.proto\x12\vdts.service\x1a\x13dts/task/task.proto\x1a\x19dts/task/task_state.proto\x1a\x15dts/error/error.proto\",\n" +
	"\x11CancelTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"Q\n" +
	"\x13GetJobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12#\n" +
	"\rinclude_tasks\x18\x02 \x01(\bR\fincludeTasks\"/\n" +
	"\x10SubscribeRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"\xa8\x01\n" +
	"\x10SubmitDagRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12$\n" +
	"\x05tasks\x18\x02 \x03(\v2\x0e.dts.task.TaskR\x05tasks\x12(\n" +
	"\x05edges\x18\x03 \x03(\v2\x12.dts.task.TaskEdgeR\x05edges\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\"e\n" +
	"\rRpcRespHeader\x12+\n" +
	"\x05error\x18\x01 \x01(\v2\x10.dts.error.ErrorH\x00R\x05error\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestIdB\b\n" +
	"\x06_error\"^\n" +
	"\x11SubmitDagResponse\x122\n" +
	"\x06header\x18\x01 \x01(\v2\x1a.dts.service.RpcRespHeaderR\x06header\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\"b\n" +
	"\x12CancelTaskResponse\x122\n" +
	"\x06header\x18\x01 \x01(\v2\x1a.dts.service.RpcRespHeaderR\x06header\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\xd5\x02\n" +
	"\x14GetJobStatusResponse\x122\n" +
	"\x06header\x18\x01 \x01(\v2\x1a.dts.service.RpcRespHeaderR\x06header\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12(\n" +
	"\x05state\x18\x03 \x01(\x0e2\x12.dts.task.JobStateR\x05state\x12\x1f\n" +
	"\vtotal_tasks\x18\x04 \x01(\x05R\n" +
	"totalTasks\x12%\n" +
	"\x0efinished_tasks\x18\x05 \x01(\x05R\rfinishedTasks\x12>\n" +
	"\ftask_details\x18\x06 \x03(\v2\x1b.dts.task.TaskRuntimeDetailR\vtaskDetails\x12\x1f\n" +
	"\vsubmit_time\x18\a \x01(\x03R\n" +
	"submitTime\x12\x1f\n" +
	"\vfinish_time\x18\b \x01(\x03R\n" +
	"finishTime\"d\n" +
	"\n" +
	"TaskResult\x122\n" +
	"\x06header\x18\x01 \x01(\v2\x1a.dts.service.RpcRespHeaderR\x06header\x12\"\n" +
	"\x04task\x18\x02 \x01(\v2\x0e.dts.task.TaskR\x04task2\xc8\x02\n" +
	"\vTaskService\x12J\n" +
	"\tSubmitDag\x12\x1d.dts.service.SubmitDagRequest\x1a\x1e.dts.service.SubmitDagResponse\x12M\n" +
	"\n" +
	"CancelTask\x12\x1e.dts.service.CancelTaskRequest\x1a\x1f.dts.service.CancelTaskResponse\x12S\n" +
	"\fGetJobStatus\x12 .dts.service.GetJobStatusRequest\x1a!.dts.service.GetJobStatusResponse\x12I\n" +
	"\rListenResults\x12\x1d.dts.service.SubscribeRequest\x1a\x17.dts.service.TaskResult0\x01B\x1bZ\x19dts-cli/pkg/proto/serviceb\x06proto3"

var (
	file_dts_service_task_service_proto_rawDescOnce sync.Once
	file_dts_service_task_service_proto_rawDescData []byte
)

func file_dts_service_task_service_proto_rawDescGZIP() []byte {
	file_dts_service_task_service_proto_rawDescOnce.Do(func() {
		file_dts_service_task_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dts_service_task_service_proto_rawDesc), len(file_dts_service_task_service_proto_rawDesc)))
	})
	return file_dts_service_task_service_proto_rawDescData
}

var file_dts_service_task_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_dts_service_task_service_proto_goTypes = []any{
	(*CancelTaskRequest)(nil),      // 0: dts.service.CancelTaskRequest
	(*GetJobStatusRequest)(nil),    // 1: dts.service.GetJobStatusRequest
	(*SubscribeRequest)(nil),       // 2: dts.service.SubscribeRequest
	(*SubmitDagRequest)(nil),       // 3: dts.service.SubmitDagRequest
	(*RpcRespHeader)(nil),          // 4: dts.service.RpcRespHeader
	(*SubmitDagResponse)(nil),      // 5: dts.service.SubmitDagResponse
	(*CancelTaskResponse)(nil),     // 6: dts.service.CancelTaskResponse
	(*GetJobStatusResponse)(nil),   // 7: dts.service.GetJobStatusResponse
	(*TaskResult)(nil),             // 8: dts.service.TaskResult
	(*task.Task)(nil),              // 9: dts.task.Task
	(*task.TaskEdge)(nil),          // 10: dts.task.TaskEdge
	(*error1.Error)(nil),           // 11: dts.error.Error
	(task.JobState)(0),             // 12: dts.task.JobState
	(*task.TaskRuntimeDetail)(nil), // 13: dts.task.TaskRuntimeDetail
}
var file_dts_service_task_service_proto_depIdxs = []int32{
	9,  // 0: dts.service.SubmitDagRequest.tasks:type_name -> dts.task.Task
	10, // 1: dts.service.SubmitDagRequest.edges:type_name -> dts.task.TaskEdge
	11, // 2: dts.service.RpcRespHeader.error:type_name -> dts.error.Error
	4,  // 3: dts.service.SubmitDagResponse.header:type_name -> dts.service.RpcRespHeader
	4,  // 4: dts.service.CancelTaskResponse.header:type_name -> dts.service.RpcRespHeader
	4,  // 5: dts.service.GetJobStatusResponse.header:type_name -> dts.service.RpcRespHeader
	12, // 6: dts.service.GetJobStatusResponse.state:type_name -> dts.task.JobState
	13, // 7: dts.service.GetJobStatusResponse.task_details:type_name -> dts.task.TaskRuntimeDetail
	4,  // 8: dts.service.TaskResult.header:type_name -> dts.service.RpcRespHeader
	9,  // 9: dts.service.TaskResult.task:type_name -> dts.task.Task
	3,  // 10: dts.service.TaskService.SubmitDag:input_type -> dts.service.SubmitDagRequest
	0,  // 11: dts.service.TaskService.CancelTask:input_type -> dts.service.CancelTaskRequest
	1,  // 12: dts.service.TaskService.GetJobStatus:input_type -> dts.service.GetJobStatusRequest
	2,  // 13: dts.service.TaskService.ListenResults:input_type -> dts.service.SubscribeRequest
	5,  // 14: dts.service.TaskService.SubmitDag:output_type -> dts.service.SubmitDagResponse
	6,  // 15: dts.service.TaskService.CancelTask:output_type -> dts.service.CancelTaskResponse
	7,  // 16: dts.service.TaskService.GetJobStatus:output_type -> dts.service.GetJobStatusResponse
	8,  // 17: dts.service.TaskService.ListenResults:output_type -> dts.service.TaskResult
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_dts_service_task_service_proto_init() }
func file_dts_service_task_service_proto_init() {
	if File_dts_service_task_service_proto != nil {
		return
	}
	file_dts_service_task_service_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dts_service_task_service_proto_rawDesc), len(file_dts_service_task_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dts_service_task_service_proto_goTypes,
		DependencyIndexes: file_dts_service_task_service_proto_depIdxs,
		MessageInfos:      file_dts_service_task_service_proto_msgTypes,
	}.Build()
	File_dts_service_task_service_proto = out.File
	file_dts_service_task_service_proto_goTypes = nil
	file_dts_service_task_service_proto_depIdxs = nil
}
