syntax = "proto3";
package dts.task;

import "google/protobuf/struct.proto";
import "dts/common/resource.proto";
import "dts/common/shard.proto";
import "dts/task/task_state.proto";

option go_package = "dts-cli/pkg/proto/task";

message TaskEdge {
  string parent_natural_id = 1; 
  string child_natural_id  = 2; 
}

message TaskRuntimeDetail {
  string task_id = 1;
  TaskState state = 2;
  string worker_id = 3;       // 哪个 Worker 执行的（排查问题很有用）
  string error_message = 4;   // 如果失败，错误信息
  int32 retry_count = 5;      // 已重试次数
  int64 start_time = 6;       // Unix Timestamp (ms)
  int64 end_time = 7;         // Unix Timestamp (ms)
  string result_payload = 8;  // (可选) 任务产出的简短结果
}

message Task {
  string task_id     = 1;  
  string natural_id  = 17; 

  
  string job_id      = 18; 
  int32 pending_dependencies = 19; 
  

  string client_id   = 2;
  uint32 priority    = 3;
  TaskState state    = 4;
  string func_name   = 5;
  string func_params = 6;
  dts.common.Resource required = 7;
  dts.common.Shard shard       = 8;
  uint32 timeout_ms  = 9;
  uint32 max_retry   = 10;
  uint32 retry_count = 11;
  int64  submit_ts   = 12;
  int64  start_ts    = 13;
  int64  finish_ts   = 14;
  google.protobuf.Struct result = 15;
  string error_msg   = 16;
}

