// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: dts/error/error.proto

package error

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Code:
	//
	//	*Error_Sys
	//	*Error_Job
	Code          isError_Code `protobuf_oneof:"code"`
	Msg           string       `protobuf:"bytes,10,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_dts_error_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_dts_error_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_dts_error_error_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() isError_Code {
	if x != nil {
		return x.Code
	}
	return nil
}

func (x *Error) GetSys() SysErr {
	if x != nil {
		if x, ok := x.Code.(*Error_Sys); ok {
			return x.Sys
		}
	}
	return SysErr_SYS_ERR_UNSPECIFIED
}

func (x *Error) GetJob() JobErr {
	if x != nil {
		if x, ok := x.Code.(*Error_Job); ok {
			return x.Job
		}
	}
	return JobErr_JOB_ERR_UNSPECIFIED
}

func (x *Error) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type isError_Code interface {
	isError_Code()
}

type Error_Sys struct {
	Sys SysErr `protobuf:"varint,1,opt,name=sys,proto3,enum=dts.error.SysErr,oneof"`
}

type Error_Job struct {
	Job JobErr `protobuf:"varint,2,opt,name=job,proto3,enum=dts.error.JobErr,oneof"`
}

func (*Error_Sys) isError_Code() {}

func (*Error_Job) isError_Code() {}

var File_dts_error_error_proto protoreflect.FileDescriptor

const file_dts_error_error_proto_rawDesc = "" +
	"\n" +
	"\x15dts/error/error.proto\x12\tdts.error\x1a\x19dts/error/sys_error.proto\x1a\x19dts/error/job_error.proto\"o\n" +
	"\x05Error\x12%\n" +
	"\x03sys\x18\x01 \x01(\x0e2\x11.dts.error.SysErrH\x00R\x03sys\x12%\n" +
	"\x03job\x18\x02 \x01(\x0e2\x11.dts.error.JobErrH\x00R\x03job\x12\x10\n" +
	"\x03msg\x18\n" +
	" \x01(\tR\x03msgB\x06\n" +
	"\x04codeB\x19Z\x17dts-cli/pkg/proto/errorb\x06proto3"

var (
	file_dts_error_error_proto_rawDescOnce sync.Once
	file_dts_error_error_proto_rawDescData []byte
)

func file_dts_error_error_proto_rawDescGZIP() []byte {
	file_dts_error_error_proto_rawDescOnce.Do(func() {
		file_dts_error_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dts_error_error_proto_rawDesc), len(file_dts_error_error_proto_rawDesc)))
	})
	return file_dts_error_error_proto_rawDescData
}

var file_dts_error_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dts_error_error_proto_goTypes = []any{
	(*Error)(nil), // 0: dts.error.Error
	(SysErr)(0),   // 1: dts.error.SysErr
	(JobErr)(0),   // 2: dts.error.JobErr
}
var file_dts_error_error_proto_depIdxs = []int32{
	1, // 0: dts.error.Error.sys:type_name -> dts.error.SysErr
	2, // 1: dts.error.Error.job:type_name -> dts.error.JobErr
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dts_error_error_proto_init() }
func file_dts_error_error_proto_init() {
	if File_dts_error_error_proto != nil {
		return
	}
	file_dts_error_sys_error_proto_init()
	file_dts_error_job_error_proto_init()
	file_dts_error_error_proto_msgTypes[0].OneofWrappers = []any{
		(*Error_Sys)(nil),
		(*Error_Job)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dts_error_error_proto_rawDesc), len(file_dts_error_error_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dts_error_error_proto_goTypes,
		DependencyIndexes: file_dts_error_error_proto_depIdxs,
		MessageInfos:      file_dts_error_error_proto_msgTypes,
	}.Build()
	File_dts_error_error_proto = out.File
	file_dts_error_error_proto_goTypes = nil
	file_dts_error_error_proto_depIdxs = nil
}
