// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: dts/error/job_error.proto

package error

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobErr int32

const (
	JobErr_JOB_ERR_UNSPECIFIED JobErr = 0
	JobErr_JOB_NOT_FOUND       JobErr = 1
	JobErr_JOB_TIMEOUT         JobErr = 2
)

// Enum value maps for JobErr.
var (
	JobErr_name = map[int32]string{
		0: "JOB_ERR_UNSPECIFIED",
		1: "JOB_NOT_FOUND",
		2: "JOB_TIMEOUT",
	}
	JobErr_value = map[string]int32{
		"JOB_ERR_UNSPECIFIED": 0,
		"JOB_NOT_FOUND":       1,
		"JOB_TIMEOUT":         2,
	}
)

func (x JobErr) Enum() *JobErr {
	p := new(JobErr)
	*p = x
	return p
}

func (x JobErr) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobErr) Descriptor() protoreflect.EnumDescriptor {
	return file_dts_error_job_error_proto_enumTypes[0].Descriptor()
}

func (JobErr) Type() protoreflect.EnumType {
	return &file_dts_error_job_error_proto_enumTypes[0]
}

func (x JobErr) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobErr.Descriptor instead.
func (JobErr) EnumDescriptor() ([]byte, []int) {
	return file_dts_error_job_error_proto_rawDescGZIP(), []int{0}
}

var File_dts_error_job_error_proto protoreflect.FileDescriptor

const file_dts_error_job_error_proto_rawDesc = "" +
	"\n" +
	"\x19dts/error/job_error.proto\x12\tdts.error*E\n" +
	"\x06JobErr\x12\x17\n" +
	"\x13JOB_ERR_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rJOB_NOT_FOUND\x10\x01\x12\x0f\n" +
	"\vJOB_TIMEOUT\x10\x02B\x19Z\x17dts-cli/pkg/proto/errorb\x06proto3"

var (
	file_dts_error_job_error_proto_rawDescOnce sync.Once
	file_dts_error_job_error_proto_rawDescData []byte
)

func file_dts_error_job_error_proto_rawDescGZIP() []byte {
	file_dts_error_job_error_proto_rawDescOnce.Do(func() {
		file_dts_error_job_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dts_error_job_error_proto_rawDesc), len(file_dts_error_job_error_proto_rawDesc)))
	})
	return file_dts_error_job_error_proto_rawDescData
}

var file_dts_error_job_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dts_error_job_error_proto_goTypes = []any{
	(JobErr)(0), // 0: dts.error.JobErr
}
var file_dts_error_job_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dts_error_job_error_proto_init() }
func file_dts_error_job_error_proto_init() {
	if File_dts_error_job_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dts_error_job_error_proto_rawDesc), len(file_dts_error_job_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dts_error_job_error_proto_goTypes,
		DependencyIndexes: file_dts_error_job_error_proto_depIdxs,
		EnumInfos:         file_dts_error_job_error_proto_enumTypes,
	}.Build()
	File_dts_error_job_error_proto = out.File
	file_dts_error_job_error_proto_goTypes = nil
	file_dts_error_job_error_proto_depIdxs = nil
}
