// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: dts/error/sys_error.proto

package error

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SysErr int32

const (
	SysErr_SYS_ERR_UNSPECIFIED SysErr = 0
	SysErr_SYS_INVALID_PARAM   SysErr = 1
	SysErr_SYS_RATE_LIMITED    SysErr = 2
	SysErr_SYS_IDEMPOTENT      SysErr = 3
	SysErr_SYS_INTERNAL        SysErr = 4
)

// Enum value maps for SysErr.
var (
	SysErr_name = map[int32]string{
		0: "SYS_ERR_UNSPECIFIED",
		1: "SYS_INVALID_PARAM",
		2: "SYS_RATE_LIMITED",
		3: "SYS_IDEMPOTENT",
		4: "SYS_INTERNAL",
	}
	SysErr_value = map[string]int32{
		"SYS_ERR_UNSPECIFIED": 0,
		"SYS_INVALID_PARAM":   1,
		"SYS_RATE_LIMITED":    2,
		"SYS_IDEMPOTENT":      3,
		"SYS_INTERNAL":        4,
	}
)

func (x SysErr) Enum() *SysErr {
	p := new(SysErr)
	*p = x
	return p
}

func (x SysErr) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SysErr) Descriptor() protoreflect.EnumDescriptor {
	return file_dts_error_sys_error_proto_enumTypes[0].Descriptor()
}

func (SysErr) Type() protoreflect.EnumType {
	return &file_dts_error_sys_error_proto_enumTypes[0]
}

func (x SysErr) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SysErr.Descriptor instead.
func (SysErr) EnumDescriptor() ([]byte, []int) {
	return file_dts_error_sys_error_proto_rawDescGZIP(), []int{0}
}

var File_dts_error_sys_error_proto protoreflect.FileDescriptor

const file_dts_error_sys_error_proto_rawDesc = "" +
	"\n" +
	"\x19dts/error/sys_error.proto\x12\tdts.error*t\n" +
	"\x06SysErr\x12\x17\n" +
	"\x13SYS_ERR_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11SYS_INVALID_PARAM\x10\x01\x12\x14\n" +
	"\x10SYS_RATE_LIMITED\x10\x02\x12\x12\n" +
	"\x0eSYS_IDEMPOTENT\x10\x03\x12\x10\n" +
	"\fSYS_INTERNAL\x10\x04B\x19Z\x17dts-cli/pkg/proto/errorb\x06proto3"

var (
	file_dts_error_sys_error_proto_rawDescOnce sync.Once
	file_dts_error_sys_error_proto_rawDescData []byte
)

func file_dts_error_sys_error_proto_rawDescGZIP() []byte {
	file_dts_error_sys_error_proto_rawDescOnce.Do(func() {
		file_dts_error_sys_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dts_error_sys_error_proto_rawDesc), len(file_dts_error_sys_error_proto_rawDesc)))
	})
	return file_dts_error_sys_error_proto_rawDescData
}

var file_dts_error_sys_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dts_error_sys_error_proto_goTypes = []any{
	(SysErr)(0), // 0: dts.error.SysErr
}
var file_dts_error_sys_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dts_error_sys_error_proto_init() }
func file_dts_error_sys_error_proto_init() {
	if File_dts_error_sys_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dts_error_sys_error_proto_rawDesc), len(file_dts_error_sys_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dts_error_sys_error_proto_goTypes,
		DependencyIndexes: file_dts_error_sys_error_proto_depIdxs,
		EnumInfos:         file_dts_error_sys_error_proto_enumTypes,
	}.Build()
	File_dts_error_sys_error_proto = out.File
	file_dts_error_sys_error_proto_goTypes = nil
	file_dts_error_sys_error_proto_depIdxs = nil
}
