// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: dts/common/resource.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuCore       float64                `protobuf:"fixed64,1,opt,name=cpu_core,json=cpuCore,proto3" json:"cpu_core,omitempty"`
	MemMb         uint64                 `protobuf:"varint,2,opt,name=mem_mb,json=memMb,proto3" json:"mem_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_dts_common_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_dts_common_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_dts_common_resource_proto_rawDescGZIP(), []int{0}
}

func (x *Resource) GetCpuCore() float64 {
	if x != nil {
		return x.CpuCore
	}
	return 0
}

func (x *Resource) GetMemMb() uint64 {
	if x != nil {
		return x.MemMb
	}
	return 0
}

var File_dts_common_resource_proto protoreflect.FileDescriptor

const file_dts_common_resource_proto_rawDesc = "" +
	"\n" +
	"\x19dts/common/resource.proto\x12\n" +
	"dts.common\"<\n" +
	"\bResource\x12\x19\n" +
	"\bcpu_core\x18\x01 \x01(\x01R\acpuCore\x12\x15\n" +
	"\x06mem_mb\x18\x02 \x01(\x04R\x05memMbB\x1aZ\x18dts-cli/pkg/proto/commonb\x06proto3"

var (
	file_dts_common_resource_proto_rawDescOnce sync.Once
	file_dts_common_resource_proto_rawDescData []byte
)

func file_dts_common_resource_proto_rawDescGZIP() []byte {
	file_dts_common_resource_proto_rawDescOnce.Do(func() {
		file_dts_common_resource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dts_common_resource_proto_rawDesc), len(file_dts_common_resource_proto_rawDesc)))
	})
	return file_dts_common_resource_proto_rawDescData
}

var file_dts_common_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dts_common_resource_proto_goTypes = []any{
	(*Resource)(nil), // 0: dts.common.Resource
}
var file_dts_common_resource_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dts_common_resource_proto_init() }
func file_dts_common_resource_proto_init() {
	if File_dts_common_resource_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dts_common_resource_proto_rawDesc), len(file_dts_common_resource_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dts_common_resource_proto_goTypes,
		DependencyIndexes: file_dts_common_resource_proto_depIdxs,
		MessageInfos:      file_dts_common_resource_proto_msgTypes,
	}.Build()
	File_dts_common_resource_proto = out.File
	file_dts_common_resource_proto_goTypes = nil
	file_dts_common_resource_proto_depIdxs = nil
}
