// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: dts/task/task_state.proto

package task

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobState int32

const (
	JobState_JOB_UNKNOWN JobState = 0
	JobState_JOB_PENDING JobState = 1
	JobState_JOB_RUNNING JobState = 2
	JobState_JOB_SUCCESS JobState = 3
	JobState_JOB_FAILED  JobState = 4
)

// Enum value maps for JobState.
var (
	JobState_name = map[int32]string{
		0: "JOB_UNKNOWN",
		1: "JOB_PENDING",
		2: "JOB_RUNNING",
		3: "JOB_SUCCESS",
		4: "JOB_FAILED",
	}
	JobState_value = map[string]int32{
		"JOB_UNKNOWN": 0,
		"JOB_PENDING": 1,
		"JOB_RUNNING": 2,
		"JOB_SUCCESS": 3,
		"JOB_FAILED":  4,
	}
)

func (x JobState) Enum() *JobState {
	p := new(JobState)
	*p = x
	return p
}

func (x JobState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobState) Descriptor() protoreflect.EnumDescriptor {
	return file_dts_task_task_state_proto_enumTypes[0].Descriptor()
}

func (JobState) Type() protoreflect.EnumType {
	return &file_dts_task_task_state_proto_enumTypes[0]
}

func (x JobState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobState.Descriptor instead.
func (JobState) EnumDescriptor() ([]byte, []int) {
	return file_dts_task_task_state_proto_rawDescGZIP(), []int{0}
}

type TaskState int32

const (
	TaskState_PENDING      TaskState = 0
	TaskState_RUNNING      TaskState = 1
	TaskState_SUCCESS      TaskState = 2
	TaskState_FAILED       TaskState = 3
	TaskState_TIMEOUT      TaskState = 4
	TaskState_CANCELLED    TaskState = 5
	TaskState_WAITING_DEPS TaskState = 6
)

// Enum value maps for TaskState.
var (
	TaskState_name = map[int32]string{
		0: "PENDING",
		1: "RUNNING",
		2: "SUCCESS",
		3: "FAILED",
		4: "TIMEOUT",
		5: "CANCELLED",
		6: "WAITING_DEPS",
	}
	TaskState_value = map[string]int32{
		"PENDING":      0,
		"RUNNING":      1,
		"SUCCESS":      2,
		"FAILED":       3,
		"TIMEOUT":      4,
		"CANCELLED":    5,
		"WAITING_DEPS": 6,
	}
)

func (x TaskState) Enum() *TaskState {
	p := new(TaskState)
	*p = x
	return p
}

func (x TaskState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskState) Descriptor() protoreflect.EnumDescriptor {
	return file_dts_task_task_state_proto_enumTypes[1].Descriptor()
}

func (TaskState) Type() protoreflect.EnumType {
	return &file_dts_task_task_state_proto_enumTypes[1]
}

func (x TaskState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskState.Descriptor instead.
func (TaskState) EnumDescriptor() ([]byte, []int) {
	return file_dts_task_task_state_proto_rawDescGZIP(), []int{1}
}

var File_dts_task_task_state_proto protoreflect.FileDescriptor

const file_dts_task_task_state_proto_rawDesc = "" +
	"\n" +
	"\x19dts/task/task_state.proto\x12\bdts.task*^\n" +
	"\bJobState\x12\x0f\n" +
	"\vJOB_UNKNOWN\x10\x00\x12\x0f\n" +
	"\vJOB_PENDING\x10\x01\x12\x0f\n" +
	"\vJOB_RUNNING\x10\x02\x12\x0f\n" +
	"\vJOB_SUCCESS\x10\x03\x12\x0e\n" +
	"\n" +
	"JOB_FAILED\x10\x04*l\n" +
	"\tTaskState\x12\v\n" +
	"\aPENDING\x10\x00\x12\v\n" +
	"\aRUNNING\x10\x01\x12\v\n" +
	"\aSUCCESS\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03\x12\v\n" +
	"\aTIMEOUT\x10\x04\x12\r\n" +
	"\tCANCELLED\x10\x05\x12\x10\n" +
	"\fWAITING_DEPS\x10\x06B\x18Z\x16dts-cli/pkg/proto/taskb\x06proto3"

var (
	file_dts_task_task_state_proto_rawDescOnce sync.Once
	file_dts_task_task_state_proto_rawDescData []byte
)

func file_dts_task_task_state_proto_rawDescGZIP() []byte {
	file_dts_task_task_state_proto_rawDescOnce.Do(func() {
		file_dts_task_task_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dts_task_task_state_proto_rawDesc), len(file_dts_task_task_state_proto_rawDesc)))
	})
	return file_dts_task_task_state_proto_rawDescData
}

var file_dts_task_task_state_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_dts_task_task_state_proto_goTypes = []any{
	(JobState)(0),  // 0: dts.task.JobState
	(TaskState)(0), // 1: dts.task.TaskState
}
var file_dts_task_task_state_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dts_task_task_state_proto_init() }
func file_dts_task_task_state_proto_init() {
	if File_dts_task_task_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dts_task_task_state_proto_rawDesc), len(file_dts_task_task_state_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dts_task_task_state_proto_goTypes,
		DependencyIndexes: file_dts_task_task_state_proto_depIdxs,
		EnumInfos:         file_dts_task_task_state_proto_enumTypes,
	}.Build()
	File_dts_task_task_state_proto = out.File
	file_dts_task_task_state_proto_goTypes = nil
	file_dts_task_task_state_proto_depIdxs = nil
}
