// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: dts/task/task.proto

package task

import (
	common "dts-cli/pkg/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskEdge struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ParentNaturalId string                 `protobuf:"bytes,1,opt,name=parent_natural_id,json=parentNaturalId,proto3" json:"parent_natural_id,omitempty"`
	ChildNaturalId  string                 `protobuf:"bytes,2,opt,name=child_natural_id,json=childNaturalId,proto3" json:"child_natural_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskEdge) Reset() {
	*x = TaskEdge{}
	mi := &file_dts_task_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEdge) ProtoMessage() {}

func (x *TaskEdge) ProtoReflect() protoreflect.Message {
	mi := &file_dts_task_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEdge.ProtoReflect.Descriptor instead.
func (*TaskEdge) Descriptor() ([]byte, []int) {
	return file_dts_task_task_proto_rawDescGZIP(), []int{0}
}

func (x *TaskEdge) GetParentNaturalId() string {
	if x != nil {
		return x.ParentNaturalId
	}
	return ""
}

func (x *TaskEdge) GetChildNaturalId() string {
	if x != nil {
		return x.ChildNaturalId
	}
	return ""
}

type TaskRuntimeDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        TaskState              `protobuf:"varint,2,opt,name=status,proto3,enum=dts.task.TaskState" json:"status,omitempty"`
	WorkerId      string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`                // 哪个 Worker 执行的（排查问题很有用）
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`    // 如果失败，错误信息
	RetryCount    int32                  `protobuf:"varint,5,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`         // 已重试次数
	StartTime     int64                  `protobuf:"varint,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`            // Unix Timestamp (ms)
	EndTime       int64                  `protobuf:"varint,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`                  // Unix Timestamp (ms)
	ResultPayload string                 `protobuf:"bytes,8,opt,name=result_payload,json=resultPayload,proto3" json:"result_payload,omitempty"` // (可选) 任务产出的简短结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRuntimeDetail) Reset() {
	*x = TaskRuntimeDetail{}
	mi := &file_dts_task_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRuntimeDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRuntimeDetail) ProtoMessage() {}

func (x *TaskRuntimeDetail) ProtoReflect() protoreflect.Message {
	mi := &file_dts_task_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRuntimeDetail.ProtoReflect.Descriptor instead.
func (*TaskRuntimeDetail) Descriptor() ([]byte, []int) {
	return file_dts_task_task_proto_rawDescGZIP(), []int{1}
}

func (x *TaskRuntimeDetail) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskRuntimeDetail) GetStatus() TaskState {
	if x != nil {
		return x.Status
	}
	return TaskState_PENDING
}

func (x *TaskRuntimeDetail) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *TaskRuntimeDetail) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TaskRuntimeDetail) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *TaskRuntimeDetail) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *TaskRuntimeDetail) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *TaskRuntimeDetail) GetResultPayload() string {
	if x != nil {
		return x.ResultPayload
	}
	return ""
}

type Task struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TaskId              string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	NaturalId           string                 `protobuf:"bytes,17,opt,name=natural_id,json=naturalId,proto3" json:"natural_id,omitempty"`
	JobId               string                 `protobuf:"bytes,18,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	PendingDependencies int32                  `protobuf:"varint,19,opt,name=pending_dependencies,json=pendingDependencies,proto3" json:"pending_dependencies,omitempty"`
	ClientId            string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Priority            uint32                 `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	State               TaskState              `protobuf:"varint,4,opt,name=state,proto3,enum=dts.task.TaskState" json:"state,omitempty"`
	FuncName            string                 `protobuf:"bytes,5,opt,name=func_name,json=funcName,proto3" json:"func_name,omitempty"`
	FuncParams          string                 `protobuf:"bytes,6,opt,name=func_params,json=funcParams,proto3" json:"func_params,omitempty"`
	Required            *common.Resource       `protobuf:"bytes,7,opt,name=required,proto3" json:"required,omitempty"`
	Shard               *common.Shard          `protobuf:"bytes,8,opt,name=shard,proto3" json:"shard,omitempty"`
	TimeoutMs           uint32                 `protobuf:"varint,9,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	MaxRetry            uint32                 `protobuf:"varint,10,opt,name=max_retry,json=maxRetry,proto3" json:"max_retry,omitempty"`
	RetryCount          uint32                 `protobuf:"varint,11,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	SubmitTs            int64                  `protobuf:"varint,12,opt,name=submit_ts,json=submitTs,proto3" json:"submit_ts,omitempty"`
	StartTs             int64                  `protobuf:"varint,13,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	FinishTs            int64                  `protobuf:"varint,14,opt,name=finish_ts,json=finishTs,proto3" json:"finish_ts,omitempty"`
	Result              *structpb.Struct       `protobuf:"bytes,15,opt,name=result,proto3" json:"result,omitempty"`
	ErrorMsg            string                 `protobuf:"bytes,16,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_dts_task_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_dts_task_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_dts_task_task_proto_rawDescGZIP(), []int{2}
}

func (x *Task) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Task) GetNaturalId() string {
	if x != nil {
		return x.NaturalId
	}
	return ""
}

func (x *Task) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Task) GetPendingDependencies() int32 {
	if x != nil {
		return x.PendingDependencies
	}
	return 0
}

func (x *Task) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Task) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Task) GetState() TaskState {
	if x != nil {
		return x.State
	}
	return TaskState_PENDING
}

func (x *Task) GetFuncName() string {
	if x != nil {
		return x.FuncName
	}
	return ""
}

func (x *Task) GetFuncParams() string {
	if x != nil {
		return x.FuncParams
	}
	return ""
}

func (x *Task) GetRequired() *common.Resource {
	if x != nil {
		return x.Required
	}
	return nil
}

func (x *Task) GetShard() *common.Shard {
	if x != nil {
		return x.Shard
	}
	return nil
}

func (x *Task) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *Task) GetMaxRetry() uint32 {
	if x != nil {
		return x.MaxRetry
	}
	return 0
}

func (x *Task) GetRetryCount() uint32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *Task) GetSubmitTs() int64 {
	if x != nil {
		return x.SubmitTs
	}
	return 0
}

func (x *Task) GetStartTs() int64 {
	if x != nil {
		return x.StartTs
	}
	return 0
}

func (x *Task) GetFinishTs() int64 {
	if x != nil {
		return x.FinishTs
	}
	return 0
}

func (x *Task) GetResult() *structpb.Struct {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Task) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

var File_dts_task_task_proto protoreflect.FileDescriptor

const file_dts_task_task_proto_rawDesc = "" +
	"\n" +
	"\x13dts/task/task.proto\x12\bdts.task\x1a\x1cgoogle/protobuf/struct.proto\x1a\x19dts/common/resource.proto\x1a\x16dts/common/shard.proto\x1a\x19dts/task/task_state.proto\"`\n" +
	"\bTaskEdge\x12*\n" +
	"\x11parent_natural_id\x18\x01 \x01(\tR\x0fparentNaturalId\x12(\n" +
	"\x10child_natural_id\x18\x02 \x01(\tR\x0echildNaturalId\"\x9d\x02\n" +
	"\x11TaskRuntimeDetail\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12+\n" +
	"\x06status\x18\x02 \x01(\x0e2\x13.dts.task.TaskStateR\x06status\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vretry_count\x18\x05 \x01(\x05R\n" +
	"retryCount\x12\x1d\n" +
	"\n" +
	"start_time\x18\x06 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\a \x01(\x03R\aendTime\x12%\n" +
	"\x0eresult_payload\x18\b \x01(\tR\rresultPayload\"\x85\x05\n" +
	"\x04Task\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"natural_id\x18\x11 \x01(\tR\tnaturalId\x12\x15\n" +
	"\x06job_id\x18\x12 \x01(\tR\x05jobId\x121\n" +
	"\x14pending_dependencies\x18\x13 \x01(\x05R\x13pendingDependencies\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\rR\bpriority\x12)\n" +
	"\x05state\x18\x04 \x01(\x0e2\x13.dts.task.TaskStateR\x05state\x12\x1b\n" +
	"\tfunc_name\x18\x05 \x01(\tR\bfuncName\x12\x1f\n" +
	"\vfunc_params\x18\x06 \x01(\tR\n" +
	"funcParams\x120\n" +
	"\brequired\x18\a \x01(\v2\x14.dts.common.ResourceR\brequired\x12'\n" +
	"\x05shard\x18\b \x01(\v2\x11.dts.common.ShardR\x05shard\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\t \x01(\rR\ttimeoutMs\x12\x1b\n" +
	"\tmax_retry\x18\n" +
	" \x01(\rR\bmaxRetry\x12\x1f\n" +
	"\vretry_count\x18\v \x01(\rR\n" +
	"retryCount\x12\x1b\n" +
	"\tsubmit_ts\x18\f \x01(\x03R\bsubmitTs\x12\x19\n" +
	"\bstart_ts\x18\r \x01(\x03R\astartTs\x12\x1b\n" +
	"\tfinish_ts\x18\x0e \x01(\x03R\bfinishTs\x12/\n" +
	"\x06result\x18\x0f \x01(\v2\x17.google.protobuf.StructR\x06result\x12\x1b\n" +
	"\terror_msg\x18\x10 \x01(\tR\berrorMsgB\x18Z\x16dts-cli/pkg/proto/taskb\x06proto3"

var (
	file_dts_task_task_proto_rawDescOnce sync.Once
	file_dts_task_task_proto_rawDescData []byte
)

func file_dts_task_task_proto_rawDescGZIP() []byte {
	file_dts_task_task_proto_rawDescOnce.Do(func() {
		file_dts_task_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dts_task_task_proto_rawDesc), len(file_dts_task_task_proto_rawDesc)))
	})
	return file_dts_task_task_proto_rawDescData
}

var file_dts_task_task_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_dts_task_task_proto_goTypes = []any{
	(*TaskEdge)(nil),          // 0: dts.task.TaskEdge
	(*TaskRuntimeDetail)(nil), // 1: dts.task.TaskRuntimeDetail
	(*Task)(nil),              // 2: dts.task.Task
	(TaskState)(0),            // 3: dts.task.TaskState
	(*common.Resource)(nil),   // 4: dts.common.Resource
	(*common.Shard)(nil),      // 5: dts.common.Shard
	(*structpb.Struct)(nil),   // 6: google.protobuf.Struct
}
var file_dts_task_task_proto_depIdxs = []int32{
	3, // 0: dts.task.TaskRuntimeDetail.status:type_name -> dts.task.TaskState
	3, // 1: dts.task.Task.state:type_name -> dts.task.TaskState
	4, // 2: dts.task.Task.required:type_name -> dts.common.Resource
	5, // 3: dts.task.Task.shard:type_name -> dts.common.Shard
	6, // 4: dts.task.Task.result:type_name -> google.protobuf.Struct
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_dts_task_task_proto_init() }
func file_dts_task_task_proto_init() {
	if File_dts_task_task_proto != nil {
		return
	}
	file_dts_task_task_state_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dts_task_task_proto_rawDesc), len(file_dts_task_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dts_task_task_proto_goTypes,
		DependencyIndexes: file_dts_task_task_proto_depIdxs,
		MessageInfos:      file_dts_task_task_proto_msgTypes,
	}.Build()
	File_dts_task_task_proto = out.File
	file_dts_task_task_proto_goTypes = nil
	file_dts_task_task_proto_depIdxs = nil
}
